apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "ecommerce_db"
  DB_USER: "ecommerce"
  DB_PASSWORD: "36513411"
  SERVER_PORT: "8080"
