apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
stringData:
  DB_USER: "ecommerce"
  DB_PASSWORD: "ecommerce"
  MYSQL_USER: "ecommerce"
  MYSQL_PASSWORD: "ecommerce"
  MYSQL_ROOT_PASSWORD: "rootpassword"
