name: E-commerce CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      K3D_CLUSTER_NAME: ecommerce-cluster
      INGRESS_PORT: 18081

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build WAR with Ant
        run: ant war

      - name: Build Docker image
        run: docker build -t ecommerce-backend:latest .

      - name: Install K3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d --version

      - name: Create K3d cluster
        run: k3d cluster create $K3D_CLUSTER_NAME --wait

      - name: Configure kubeconfig
        run: |
          k3d kubeconfig get $K3D_CLUSTER_NAME > kubeconfig.yaml
          echo "KUBECONFIG=$PWD/kubeconfig.yaml" >> $GITHUB_ENV
          kubectl cluster-info

      - name: Deploy E-commerce full stack
        run: |
          kubectl apply -f k8s/ecommerce-full.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Wait for Backend pod to be ready
        run: |
          kubectl wait --namespace ecommerce --for=condition=ready pod -l app=ecommerce-backend --timeout=120s

      - name: Test Backend via Ingress with port-forward
        run: |
          kubectl port-forward -n kube-system svc/traefik $INGRESS_PORT:80 &
          PF_PID=$!
          sleep 5
          curl -H "Host: ecommerce.local" http://localhost:$INGRESS_PORT/ECommerce/ | grep -q "E-commerce System"
          kill $PF_PID
