name: E-commerce CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: 36513411
      MYSQL_ROOT_PASSWORD: rootpassword
      DB_NAME: ecommerce_db
      K3D_CLUSTER_NAME: ecommerce-cluster

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build WAR with Ant
        run: ant war

      - name: Build Docker image
        run: docker build -t ecommerce-backend:latest .

      - name: Install K3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d --version

      - name: Create K3d cluster
        run: k3d cluster create $K3D_CLUSTER_NAME --wait

      - name: Configure kubeconfig
        run: |
          k3d kubeconfig get $K3D_CLUSTER_NAME > kubeconfig.yaml
          echo "KUBECONFIG=$PWD/kubeconfig.yaml" >> $GITHUB_ENV
          kubectl cluster-info

      - name: Deploy MySQL
        run: |
          kubectl create namespace ecommerce || echo "Namespace already exists"
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/mysql-pvc.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml

          echo "Waiting for MySQL pod to be ready..."
          NAMESPACE=ecommerce
          while true; do
            READY=$(kubectl get pods -n $NAMESPACE -l app=mysql -o jsonpath='{.items[0].status.containerStatuses[0].ready}')
            if [ "$READY" == "true" ]; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 10
          done

          echo "Waiting for database initialization..."
          MYSQL_POD=$(kubectl get pod -n $NAMESPACE -l app=mysql -o jsonpath='{.items[0].metadata.name}')
          while true; do
            kubectl exec -n $NAMESPACE $MYSQL_POD -- mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e "USE $DB_NAME;" && break
            echo "Database not ready yet..."
            sleep 5
          done

          echo "Database initialized successfully!"
          kubectl logs -l app=mysql -n ecommerce

      - name: Deploy Backend
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml

          echo "Waiting for Backend pod to be ready..."
          NAMESPACE=ecommerce
          while true; do
            READY=$(kubectl get pods -n $NAMESPACE -l app=ecommerce-backend -o jsonpath='{.items[0].status.containerStatuses[0].ready}')
            if [ "$READY" == "true" ]; then
              echo "Backend is ready!"
              break
            fi
            echo "Waiting for Backend..."
            sleep 10
          done

          kubectl logs -l app=ecommerce-backend -n ecommerce

      - name: Test /products endpoint
        run: |
          BACKEND_POD=$(kubectl get pod -l app=ecommerce-backend -n ecommerce -o jsonpath='{.items[0].metadata.name}')
          RESPONSE=$(kubectl exec -n ecommerce $BACKEND_POD -- curl -s http://localhost:8080/ECommerce/products)
          echo "Products endpoint response: $RESPONSE"
          if [[ $RESPONSE == "[]" ]]; then
            echo "Error: /products endpoint returned empty list"
            exit 1
          fi
